services:
  php.dev:
    image: kytel0925/php:8.2-debian-apache-dev
    restart: unless-stopped
    volumes:
      - '.:/app'
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysql-volume:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - '${FORWARD_PHPMYADMIN_PORT:-8080}:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

volumes:
  mysql-volume:
    driver: local
