services:
  php.dev:
    image: kytel0925/php:8.2-debian-apache-dev
    restart: unless-stopped
    volumes:
      - '.:/app'
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '${RABBITMQ_PORT:-5672}:5672'
      - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq-data-volume:/var/lib/rabbitmq
      - rabbitmq-log-volume:/var/log/rabbitmq

volumes:
  rabbitmq-data-volume:
    driver: local
  rabbitmq-log-volume:
    driver: local
